version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "image-to-s3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4x1ikkv940p8"
s3_prefix = "image-to-s3"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
