AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  image-to-s3
  Upload an image and get link for it!
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  UploadAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: default
      Cors:
        AllowMethods: "'GET, POST, PUT, DELETE'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
  UploadRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getURL/
      Handler: geturl.geturl
      Runtime: nodejs14.x
      Environment:
        Variables:
          UploadBucket: !Ref S3UploadBucket
      Policies:
      - S3WritePolicy:
          BucketName: !Ref S3UploadBucket
      Events:
        UploadAssetAPI:
          Type: Api
          Properties:
            Path: /upload
            Method: get
            RestApiId: !Ref UploadAPI
  S3UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - '*'
          AllowedMethods:
          - GET
          - PUT
          - HEAD
          AllowedOrigins:
          - '*'
Outputs:
  APIendpoint:
    Description: "HTTP API endpoint URL"
    Value: !Sub https://${UploadAPI}.execute-api.${AWS::Region}.amazonaws.com
  S3UploadBucketName:
    Description: "S3 bucket used for uploads"
    Value: !Ref S3UploadBucket
